def age_grouping(age_group):
    lessthanone = age_group.query('Current_Age < 1')
    lessthanone = lessthanone['Current_Age'].count()
    lessthanfour = age_group.query('Current_Age > = 1 & Current_Age <= 4 ')
    lessthanfour = lessthanfour['Current_Age'].count()
    lessthanten = age_group.query(' Current_Age > = 5 & Current_Age <= 9 ')
    lessthanten = lessthanten['Current_Age'].count()
    lessthanfourteen = age_group.query('Current_Age > = 10 & Current_Age <= 14 ')
    lessthanfourteen = lessthanfourteen['Current_Age'].count()
    lessthannineteen = age_group.query(' Current_Age > = 15 & Current_Age <= 19 ')
    lessthannineteen = lessthannineteen['Current_Age'].count()
    lessthantwenty_four = age_group.query(' Current_Age > = 20 & Current_Age <= 24 ')
    lessthantwenty_four = lessthantwenty_four['Current_Age'].count()
    lessthantwenty_nine = age_group.query('  Current_Age > = 25 & Current_Age <= 29 ')
    lessthantwenty_nine = lessthantwenty_nine['Current_Age'].count()
    lessthanthirty_four = age_group.query(' Current_Age > = 30 & Current_Age <= 34 ')
    lessthanthirty_four = lessthanthirty_four['Current_Age'].count()
    lessthanthirty_nine = age_group.query('Current_Age > = 35 & Current_Age <= 39 ')
    lessthanthirty_nine = lessthanthirty_nine['Current_Age'].count()
    lessthanforty_four = age_group.query(' Current_Age > = 40 & Current_Age <= 44 ')
    lessthanforty_four = lessthanforty_four['Current_Age'].count()
    lessthanforty_nine = age_group.query(' Current_Age > = 45 & Current_Age <= 49 ')
    lessthanforty_nine = lessthanforty_nine['Current_Age'].count()
    fiftyplus = age_group.query(' Current_Age  >= 50 ')
    fiftyplus = fiftyplus['Current_Age'].count()
    return fiftyplus, lessthanforty_four, lessthanforty_nine, lessthanfour, lessthanfourteen, lessthannineteen, lessthanone, lessthanten, lessthanthirty_four, lessthanthirty_nine, lessthantwenty_four, lessthantwenty_nine


def pregnant_grouping(age_group):
    lessthannineteen = age_group.query(' Current_Age > = 15 & Current_Age <= 19 ')
    lessthannineteen = lessthannineteen['Current_Age'].count()
    lessthantwenty_four = age_group.query(' Current_Age > = 20 & Current_Age <= 24 ')
    lessthantwenty_four = lessthantwenty_four['Current_Age'].count()
    lessthantwenty_nine = age_group.query('  Current_Age > = 25 & Current_Age <= 29 ')
    lessthantwenty_nine = lessthantwenty_nine['Current_Age'].count()
    lessthanthirty_four = age_group.query(' Current_Age > = 30 & Current_Age <= 34 ')
    lessthanthirty_four = lessthanthirty_four['Current_Age'].count()
    lessthanthirty_nine = age_group.query('Current_Age > = 35 & Current_Age <= 39 ')
    lessthanthirty_nine = lessthanthirty_nine['Current_Age'].count()
    lessthanforty_four = age_group.query(' Current_Age > = 40 & Current_Age <= 44 ')
    lessthanforty_four = lessthanforty_four['Current_Age'].count()
    lessthanforty_nine = age_group.query(' Current_Age > = 45 & Current_Age <= 49 ')
    lessthanforty_nine = lessthanforty_nine['Current_Age'].count()
    fiftyplus = age_group.query(' Current_Age  >= 50 ')
    fiftyplus = fiftyplus['Current_Age'].count()
    return fiftyplus, lessthanforty_four, lessthanforty_nine, lessthannineteen, lessthanthirty_four, lessthanthirty_nine, lessthantwenty_four, lessthantwenty_nine
